words = [
    "atuin",
    "chezmoi",
    "dsl",
    "fzf",
    "gpgconf",
    "homebrew",
    "libnotify",
    "linuxbrew",
    "neovim",
    "nvim",
    "prezto",
    "ripgrep",
    "starship",
    "yazi",
]
