dictionaries = ["en_us"]

words = ["sforzando", "suzuki", "kashimada", "nishigauchi", "kanagawa"]

flag_words = ["todo", "fixme", "xxx"]

ignore_paths = ["node_modules/**", ".venv/**", "dist/**", "build/**", "public/**", "vendor/**"]
