[mgr]
prepend_keymap = [
  { on = "<Enter>", run = "open --interactive", desc = "Open with editor selection" },
  { on = "o", run = "open --interactive", desc = "Open with editor selection" },
  { on = "<Esc>", run = "close", desc = "Cancel input" },
  { on = "l", run = "plugin smart-enter", desc = "Enter the child directory, or open the file" },
]
