[edit]
    command = "code"
    args = ["--wait"]

[git]
    autoCommit = true
    autoPush = true
    # Relative to the source dir; keeps auto-commits in cz-emoji format
    commitMessageTemplateFile = ".commit_message.tmpl"
